version: '3'
services:
  electricity-monitor:
    build: .
    container_name: dorm_monitor
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./config.ini:/app/config.ini  # 挂载配置，保证Cookie不丢失
    environment:
      - TZ=Asia/Shanghai